
server:
  port: 7396

spring:
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  数据库
  datasource:
    url: jdbc:mysql://localhost:3306/ojsystemdb
    username: root
    password: zjh200619
    driver-class-name: com.mysql.cj.jdbc.Driver
# Redis 配置
#  redis:
#    database: 1
#    host: localhost
#    port: 6379
#    timeout: 5000
# 配置MyBatis日志
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

